if(EXISTS "/workspaces/cansw_processor_canards/build_test/tests/test_quaternion[1]_tests.cmake")
  include("/workspaces/cansw_processor_canards/build_test/tests/test_quaternion[1]_tests.cmake")
else()
  add_test(test_quaternion_NOT_BUILT test_quaternion_NOT_BUILT)
endif()
