add_test( GpioTest.InitCreatesMutexes /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.InitCreatesMutexes]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.InitCreatesMutexes PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.InitFailsIfMutexCreationFails /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.InitFailsIfMutexCreationFails]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.InitFailsIfMutexCreationFails PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.ReadReturnsSuccess /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.ReadReturnsSuccess]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.ReadReturnsSuccess PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.ReadFailsIfSemaphoreNotTaken /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.ReadFailsIfSemaphoreNotTaken]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.ReadFailsIfSemaphoreNotTaken PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.ReadInvalidPinReturnsError /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.ReadInvalidPinReturnsError]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.ReadInvalidPinReturnsError PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.WriteSetsPinHigh /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.WriteSetsPinHigh]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.WriteSetsPinHigh PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.WriteSetsPinLow /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.WriteSetsPinLow]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.WriteSetsPinLow PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.WriteFailsIfSemaphoreNotTaken /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.WriteFailsIfSemaphoreNotTaken]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.WriteFailsIfSemaphoreNotTaken PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.WriteInvalidPinReturnsError /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.WriteInvalidPinReturnsError]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.WriteInvalidPinReturnsError PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.ToggleSuccess /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.ToggleSuccess]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.ToggleSuccess PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.ToggleFailsIfSemaphoreNotTaken /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.ToggleFailsIfSemaphoreNotTaken]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.ToggleFailsIfSemaphoreNotTaken PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( GpioTest.ToggleInvalidPinReturnsError /workspaces/cansw_processor_canards/build_test/tests/test_gpio [==[--gtest_filter=GpioTest.ToggleInvalidPinReturnsError]==] --gtest_also_run_disabled_tests)
set_tests_properties( GpioTest.ToggleInvalidPinReturnsError PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( test_gpio_TESTS GpioTest.InitCreatesMutexes GpioTest.InitFailsIfMutexCreationFails GpioTest.ReadReturnsSuccess GpioTest.ReadFailsIfSemaphoreNotTaken GpioTest.ReadInvalidPinReturnsError GpioTest.WriteSetsPinHigh GpioTest.WriteSetsPinLow GpioTest.WriteFailsIfSemaphoreNotTaken GpioTest.WriteInvalidPinReturnsError GpioTest.ToggleSuccess GpioTest.ToggleFailsIfSemaphoreNotTaken GpioTest.ToggleInvalidPinReturnsError)
