if(EXISTS "/workspaces/cansw_processor_canards/build_test/tests/test_flight_phase[1]_tests.cmake")
  include("/workspaces/cansw_processor_canards/build_test/tests/test_flight_phase[1]_tests.cmake")
else()
  add_test(test_flight_phase_NOT_BUILT test_flight_phase_NOT_BUILT)
endif()
