add_test( UartTest.InitSuccess /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.InitSuccess]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.InitSuccess PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.InitInvalidParams /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.InitInvalidParams]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.InitInvalidParams PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.InitFailures /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.InitFailures]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.InitFailures PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.WriteSuccess /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.WriteSuccess]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.WriteSuccess PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.WriteInvalidParams /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.WriteInvalidParams]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.WriteInvalidParams PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.WriteTimeout /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.WriteTimeout]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.WriteTimeout PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.WriteHal /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.WriteHal]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.WriteHal PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.ReadSuccess /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.ReadSuccess]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.ReadSuccess PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.ReadTimeout /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.ReadTimeout]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.ReadTimeout PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.ReadInvalidParams /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.ReadInvalidParams]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.ReadInvalidParams PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.MessageOverflowHandling /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.MessageOverflowHandling]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.MessageOverflowHandling PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.CircularBufferHandling /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.CircularBufferHandling]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.CircularBufferHandling PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( UartTest.ErrorHandlingAndStats /workspaces/cansw_processor_canards/build_test/tests/test_uart [==[--gtest_filter=UartTest.ErrorHandlingAndStats]==] --gtest_also_run_disabled_tests)
set_tests_properties( UartTest.ErrorHandlingAndStats PROPERTIES WORKING_DIRECTORY /workspaces/cansw_processor_canards/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( test_uart_TESTS UartTest.InitSuccess UartTest.InitInvalidParams UartTest.InitFailures UartTest.WriteSuccess UartTest.WriteInvalidParams UartTest.WriteTimeout UartTest.WriteHal UartTest.ReadSuccess UartTest.ReadTimeout UartTest.ReadInvalidParams UartTest.MessageOverflowHandling UartTest.CircularBufferHandling UartTest.ErrorHandlingAndStats)
