if(EXISTS "/workspaces/cansw_processor_canards/build_test/tests/test_gpio[1]_tests.cmake")
  include("/workspaces/cansw_processor_canards/build_test/tests/test_gpio[1]_tests.cmake")
else()
  add_test(test_gpio_NOT_BUILT test_gpio_NOT_BUILT)
endif()
