if(EXISTS "/workspaces/cansw_processor_canards/build_test/tests/test_altimu[1]_tests.cmake")
  include("/workspaces/cansw_processor_canards/build_test/tests/test_altimu[1]_tests.cmake")
else()
  add_test(test_altimu_NOT_BUILT test_altimu_NOT_BUILT)
endif()
