if(EXISTS "/workspaces/cansw_processor_canards/build_test/tests/test_i2c[1]_tests.cmake")
  include("/workspaces/cansw_processor_canards/build_test/tests/test_i2c[1]_tests.cmake")
else()
  add_test(test_i2c_NOT_BUILT test_i2c_NOT_BUILT)
endif()
